# Generated by Django 3.1 on 2020-09-02 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_remove_galleryitem_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='galleryitem',
            name='direct_sale',
            field=models.BooleanField(default=False, help_text='Check this box to list this item for sale directly on your website.', verbose_name='Add to shop'),
        ),
        migrations.AddField(
            model_name='galleryitem',
            name='direct_sale_extra_description',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='galleryitem',
            name='direct_sale_price',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='galleryitem',
            name='external_print_sale_url',
            field=models.URLField(blank=True, help_text='Add an external link to sell prints (ex. Society6)'),
        ),
    ]
