# Generated by Django 3.1 on 2020-09-02 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0022_uploadedimage'),
        ('gallery', '0003_auto_20200902_1109'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Image',
            new_name='GalleryImage',
        ),
        migrations.AlterField(
            model_name='galleryitem',
            name='direct_sale',
            field=models.BooleanField(default=False, help_text='Check this box to list this item for sale directly on your website.', verbose_name='On Sale'),
        ),
        migrations.AlterField(
            model_name='galleryitem',
            name='direct_sale_extra_description',
            field=models.CharField(blank=True, max_length=250, verbose_name='Addtional sale description (optional)'),
        ),
        migrations.AlterField(
            model_name='galleryitem',
            name='direct_sale_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Sale price'),
        ),
    ]
