# Generated by Django 3.1 on 2020-09-04 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0004_auto_20200902_1423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='installationpage',
            name='use_gallery',
            field=models.BooleanField(default=True, help_text='Turn the sliding gallery on or off.', verbose_name='Use gallery images'),
        ),
    ]
