# Generated by Django 3.1 on 2020-09-04 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0005_auto_20200904_0923'),
    ]

    operations = [
        migrations.AddField(
            model_name='galleryitem',
            name='stock',
            field=models.IntegerField(blank=True, null=True, verbose_name='Number in stock'),
        ),
    ]
