# Generated by Django 3.1 on 2020-09-05 17:39

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0006_galleryitem_stock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='galleryitem',
            name='external_print_sale_url',
        ),
        migrations.AlterField(
            model_name='galleryitem',
            name='direct_sale_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Add more info about this item for the store page only.', max_digits=6, null=True, verbose_name='Sale price, $'),
        ),
        migrations.CreateModel(
            name='ExternalLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('description', models.CharField(blank=True, max_length=250)),
                ('external_print_sale_url', models.URLField(blank=True, help_text='Add an external link to sell prints (ex. Society6)')),
                ('gallery_item', modelcluster.fields.ParentalKey(help_text='Add details about the listing, ex. dimensions, framing.', on_delete=django.db.models.deletion.CASCADE, related_name='external_links', to='gallery.galleryitem')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
