# Generated by Django 3.1 on 2020-09-06 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0008_shopitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='externallink',
            name='external_print_sale_url',
        ),
        migrations.AddField(
            model_name='externallink',
            name='external_sale_url',
            field=models.URLField(blank=True, help_text='Add an external sale link (ex. Society6 prints)'),
        ),
    ]
