# Generated by Django 3.1 on 2020-09-07 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0010_shop'),
    ]

    operations = [
        migrations.AddField(
            model_name='galleryitem',
            name='external_sale',
            field=models.BooleanField(default=False, help_text='Check this box to add external sale links (ex. Society6).', verbose_name='External Sale'),
        ),
    ]
