# Generated by Django 3.1 on 2020-12-12 15:32

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0015_auto_20200911_1358'),
    ]

    operations = [
        migrations.CreateModel(
            name='DirectSaleType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'sale types',
            },
        ),
        migrations.AlterField(
            model_name='installationpage',
            name='mediums',
            field=modelcluster.fields.ParentalManyToManyField(default='Painting', help_text='Add more options by going to "Snippets" in the left hand menu.', to='gallery.InstallationMedium'),
        ),
        migrations.AlterField(
            model_name='installationpage',
            name='use_gallery',
            field=models.BooleanField(default=True, help_text='Turn the sliding gallery on or off. If you turn it off you can add your images in a custom format in the body below.', verbose_name='Use gallery images'),
        ),
        migrations.AddField(
            model_name='galleryitem',
            name='direct_sale_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gallery.directsaletype'),
        ),
    ]
