# Generated by Django 3.1 on 2020-12-12 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0016_auto_20201212_0932'),
    ]

    operations = [
        migrations.RenameField(
            model_name='directsaletype',
            old_name='name',
            new_name='direct_sale_type',
        ),
    ]
