# Generated by Django 3.1 on 2020-12-15 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0018_auto_20201212_0945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galleryitem',
            name='direct_sale_type',
            field=models.ForeignKey(default='DirectSaleType.get_default_pk', help_text='What type of item are you selling? You can add more options in the Snippets menu.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='gallery.directsaletype'),
        ),
    ]
