# Generated by Django 3.1 on 2020-12-15 14:45

from django.db import migrations
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_auto_20201212_0932'),
        ('gallery', '0019_auto_20201215_0819'),
    ]

    operations = [
        migrations.AddField(
            model_name='galleryitem',
            name='shop_page',
            field=modelcluster.fields.ParentalKey(default=407, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.shop'),
        ),
    ]
