# Generated by Django 3.1 on 2020-12-17 15:27

import datetime
from django.db import migrations, models
import django.db.models.deletion
import gallery.models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0021_remove_galleryitem_shop_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='galleryimage',
            name='set_as_main_shop_image',
            field=models.BooleanField(default=False, help_text='Make this the primary image for this item (as displayed in the shop).'),
        ),
        migrations.AddField(
            model_name='galleryitem',
            name='selected_main_shop_image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gallery.galleryimage'),
        ),
        migrations.AlterField(
            model_name='galleryitem',
            name='direct_sale_type',
            field=models.ForeignKey(default=gallery.models.DirectSaleType.get_default_pk, help_text='What type of item are you selling? You can add more options in the Snippets menu.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='gallery.directsaletype'),
        ),
        migrations.AlterField(
            model_name='installationpage',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 12, 17, 9, 27, 29, 892977), verbose_name='Post date'),
        ),
    ]
