# Generated by Django 3.1 on 2020-12-17 19:30

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0022_auto_20201217_0927'),
    ]

    operations = [
        migrations.AddField(
            model_name='galleryimage',
            name='set_as_main_gallery_image',
            field=models.BooleanField(default=False, help_text='Make this the primary image for this item (as displayed in the gallery).'),
        ),
        migrations.AddField(
            model_name='installationpage',
            name='selected_main_gallery_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gallery.galleryimage'),
        ),
        migrations.AlterField(
            model_name='galleryitem',
            name='selected_main_shop_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gallery.galleryimage'),
        ),
        migrations.AlterField(
            model_name='installationpage',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 12, 17, 13, 30, 4, 725260), verbose_name='Post date'),
        ),
    ]
