# Generated by Django 3.1 on 2020-12-19 19:16

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0024_auto_20201217_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='installationpage',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 12, 19, 19, 16, 57, 612236, tzinfo=utc), verbose_name='Post date'),
        ),
    ]
