# Generated by Django 3.1 on 2020-12-30 15:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0026_auto_20201220_0839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='installationpage',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Post date'),
        ),
    ]
