# Generated by Django 3.1 on 2020-12-30 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20200914_1557'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='slider_label',
            field=models.CharField(blank=True, default='Featured Works', max_length=60, null=True),
        ),
    ]
