# Generated by Django 3.1 on 2020-09-16 18:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gallery', '0015_auto_20200911_1358'),
        ('shop', '0003_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('processing', 'In Process'), ('success', 'Order Completed Succesfully'), ('failed', 'Order Failed')], max_length=100)),
                ('date', models.DateTimeField(editable=False)),
                ('user_username', models.CharField(max_length=320)),
                ('user_email', models.CharField(max_length=320)),
                ('items', models.ManyToManyField(to='gallery.GalleryItem')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
