# Generated by Django 3.1 on 2020-09-21 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_auto_20200920_1229'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraddress',
            name='address2',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='useraddress',
            name='first_name',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='useraddress',
            name='last_name',
            field=models.CharField(max_length=60, null=True),
        ),
    ]
