# Generated by Django 3.1 on 2020-09-24 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_auto_20200921_1522'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraddress',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='useraddress',
            name='last_name',
        ),
        migrations.AddField(
            model_name='order',
            name='first_name',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='last_name',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.useraddress'),
        ),
        migrations.AddField(
            model_name='useraddress',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
