# Generated by Django 3.1 on 2020-12-12 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_auto_20200924_0909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('processing', 'In Process, payment not submitted.'), ('success', 'Order Completed Succesfully'), ('failed', 'Order Failed')], max_length=100),
        ),
    ]
