# Generated by Django 3.1 on 2020-12-19 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_auto_20201212_0932'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='paypal_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
